// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: box.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedTransport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Padding       []byte                 `protobuf:"bytes,4,opt,name=Padding,proto3" json:"Padding,omitempty"`
	Path          uint32                 `protobuf:"varint,5,opt,name=Path,proto3" json:"Path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransport) Reset() {
	*x = SignedTransport{}
	mi := &file_box_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransport) ProtoMessage() {}

func (x *SignedTransport) ProtoReflect() protoreflect.Message {
	mi := &file_box_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransport.ProtoReflect.Descriptor instead.
func (*SignedTransport) Descriptor() ([]byte, []int) {
	return file_box_proto_rawDescGZIP(), []int{0}
}

func (x *SignedTransport) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignedTransport) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedTransport) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignedTransport) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *SignedTransport) GetPath() uint32 {
	if x != nil {
		return x.Path
	}
	return 0
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_box_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_box_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_box_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metadata) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Ratchet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dh            []byte                 `protobuf:"bytes,1,opt,name=dh,proto3,oneof" json:"dh,omitempty"`           // New DH public key (32 bytes)
	Pn            uint64                 `protobuf:"varint,2,opt,name=pn,proto3" json:"pn,omitempty"`                // Previous chain message count
	Ns            uint64                 `protobuf:"varint,3,opt,name=ns,proto3" json:"ns,omitempty"`                // Current message number in send chain
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // Ciphertext: Encrypted(SignedTransport)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ratchet) Reset() {
	*x = Ratchet{}
	mi := &file_box_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ratchet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ratchet) ProtoMessage() {}

func (x *Ratchet) ProtoReflect() protoreflect.Message {
	mi := &file_box_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ratchet.ProtoReflect.Descriptor instead.
func (*Ratchet) Descriptor() ([]byte, []int) {
	return file_box_proto_rawDescGZIP(), []int{2}
}

func (x *Ratchet) GetDh() []byte {
	if x != nil {
		return x.Dh
	}
	return nil
}

func (x *Ratchet) GetPn() uint64 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *Ratchet) GetNs() uint64 {
	if x != nil {
		return x.Ns
	}
	return 0
}

func (x *Ratchet) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_box_proto protoreflect.FileDescriptor

const file_box_proto_rawDesc = "" +
	"\n" +
	"\tbox.proto\x12\x03box\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x0fSignedTransport\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x1c\n" +
	"\tSignature\x18\x02 \x01(\fR\tSignature\x12)\n" +
	"\bMetadata\x18\x03 \x01(\v2\r.box.MetadataR\bMetadata\x12\x18\n" +
	"\aPadding\x18\x04 \x01(\fR\aPadding\x12\x12\n" +
	"\x04Path\x18\x05 \x01(\rR\x04Path\"p\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12\x1a\n" +
	"\bSequence\x18\x03 \x01(\x04R\bSequence\"e\n" +
	"\aRatchet\x12\x13\n" +
	"\x02dh\x18\x01 \x01(\fH\x00R\x02dh\x88\x01\x01\x12\x0e\n" +
	"\x02pn\x18\x02 \x01(\x04R\x02pn\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\x04R\x02ns\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertextB\x05\n" +
	"\x03_dhB\x06Z\x04./pbb\x06proto3"

var (
	file_box_proto_rawDescOnce sync.Once
	file_box_proto_rawDescData []byte
)

func file_box_proto_rawDescGZIP() []byte {
	file_box_proto_rawDescOnce.Do(func() {
		file_box_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_box_proto_rawDesc), len(file_box_proto_rawDesc)))
	})
	return file_box_proto_rawDescData
}

var file_box_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_box_proto_goTypes = []any{
	(*SignedTransport)(nil),       // 0: box.SignedTransport
	(*Metadata)(nil),              // 1: box.Metadata
	(*Ratchet)(nil),               // 2: box.Ratchet
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_box_proto_depIdxs = []int32{
	1, // 0: box.SignedTransport.Metadata:type_name -> box.Metadata
	3, // 1: box.Metadata.Timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_box_proto_init() }
func file_box_proto_init() {
	if File_box_proto != nil {
		return
	}
	file_box_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_box_proto_rawDesc), len(file_box_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_box_proto_goTypes,
		DependencyIndexes: file_box_proto_depIdxs,
		MessageInfos:      file_box_proto_msgTypes,
	}.Build()
	File_box_proto = out.File
	file_box_proto_goTypes = nil
	file_box_proto_depIdxs = nil
}
