// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: box.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route int32

const (
	Route_ROUTE_INVALID            Route = 0
	Route_ROUTE_IDENTITY           Route = 1
	Route_ROUTE_REQUEST_HANDSHAKE  Route = 2
	Route_ROUTE_ACCEPT_HANDSHAKE   Route = 3
	Route_ROUTE_FINALIZE_HANDSHAKE Route = 4
	Route_ROUTE_SEND_CHALLENGE     Route = 5
	Route_ROUTE_VERIFY_CHALLENGE   Route = 6
	Route_ROUTE_EXCHANGE_MESSAGES  Route = 7
	Route_ROUTE_CLOSE_TRANSPORT    Route = 8
)

// Enum value maps for Route.
var (
	Route_name = map[int32]string{
		0: "ROUTE_INVALID",
		1: "ROUTE_IDENTITY",
		2: "ROUTE_REQUEST_HANDSHAKE",
		3: "ROUTE_ACCEPT_HANDSHAKE",
		4: "ROUTE_FINALIZE_HANDSHAKE",
		5: "ROUTE_SEND_CHALLENGE",
		6: "ROUTE_VERIFY_CHALLENGE",
		7: "ROUTE_EXCHANGE_MESSAGES",
		8: "ROUTE_CLOSE_TRANSPORT",
	}
	Route_value = map[string]int32{
		"ROUTE_INVALID":            0,
		"ROUTE_IDENTITY":           1,
		"ROUTE_REQUEST_HANDSHAKE":  2,
		"ROUTE_ACCEPT_HANDSHAKE":   3,
		"ROUTE_FINALIZE_HANDSHAKE": 4,
		"ROUTE_SEND_CHALLENGE":     5,
		"ROUTE_VERIFY_CHALLENGE":   6,
		"ROUTE_EXCHANGE_MESSAGES":  7,
		"ROUTE_CLOSE_TRANSPORT":    8,
	}
)

func (x Route) Enum() *Route {
	p := new(Route)
	*p = x
	return p
}

func (x Route) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Route) Descriptor() protoreflect.EnumDescriptor {
	return file_box_proto_enumTypes[0].Descriptor()
}

func (Route) Type() protoreflect.EnumType {
	return &file_box_proto_enumTypes[0]
}

func (x Route) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Route.Descriptor instead.
func (Route) EnumDescriptor() ([]byte, []int) {
	return file_box_proto_rawDescGZIP(), []int{0}
}

type SignedTransport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Padding       []byte                 `protobuf:"bytes,4,opt,name=Padding,proto3" json:"Padding,omitempty"`
	Route         Route                  `protobuf:"varint,5,opt,name=Route,proto3,enum=box.Route" json:"Route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransport) Reset() {
	*x = SignedTransport{}
	mi := &file_box_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransport) ProtoMessage() {}

func (x *SignedTransport) ProtoReflect() protoreflect.Message {
	mi := &file_box_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransport.ProtoReflect.Descriptor instead.
func (*SignedTransport) Descriptor() ([]byte, []int) {
	return file_box_proto_rawDescGZIP(), []int{0}
}

func (x *SignedTransport) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignedTransport) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedTransport) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignedTransport) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *SignedTransport) GetRoute() Route {
	if x != nil {
		return x.Route
	}
	return Route_ROUTE_INVALID
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_box_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_box_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_box_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metadata) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_box_proto protoreflect.FileDescriptor

const file_box_proto_rawDesc = "" +
	"\n" +
	"\tbox.proto\x12\x03box\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\x0fSignedTransport\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x1c\n" +
	"\tSignature\x18\x02 \x01(\fR\tSignature\x12)\n" +
	"\bMetadata\x18\x03 \x01(\v2\r.box.MetadataR\bMetadata\x12\x18\n" +
	"\aPadding\x18\x04 \x01(\fR\aPadding\x12 \n" +
	"\x05Route\x18\x05 \x01(\x0e2\n" +
	".box.RouteR\x05Route\"p\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12\x1a\n" +
	"\bSequence\x18\x03 \x01(\x04R\bSequence*\xf3\x01\n" +
	"\x05Route\x12\x11\n" +
	"\rROUTE_INVALID\x10\x00\x12\x12\n" +
	"\x0eROUTE_IDENTITY\x10\x01\x12\x1b\n" +
	"\x17ROUTE_REQUEST_HANDSHAKE\x10\x02\x12\x1a\n" +
	"\x16ROUTE_ACCEPT_HANDSHAKE\x10\x03\x12\x1c\n" +
	"\x18ROUTE_FINALIZE_HANDSHAKE\x10\x04\x12\x18\n" +
	"\x14ROUTE_SEND_CHALLENGE\x10\x05\x12\x1a\n" +
	"\x16ROUTE_VERIFY_CHALLENGE\x10\x06\x12\x1b\n" +
	"\x17ROUTE_EXCHANGE_MESSAGES\x10\a\x12\x19\n" +
	"\x15ROUTE_CLOSE_TRANSPORT\x10\bB\x06Z\x04./pbb\x06proto3"

var (
	file_box_proto_rawDescOnce sync.Once
	file_box_proto_rawDescData []byte
)

func file_box_proto_rawDescGZIP() []byte {
	file_box_proto_rawDescOnce.Do(func() {
		file_box_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_box_proto_rawDesc), len(file_box_proto_rawDesc)))
	})
	return file_box_proto_rawDescData
}

var file_box_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_box_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_box_proto_goTypes = []any{
	(Route)(0),                    // 0: box.Route
	(*SignedTransport)(nil),       // 1: box.SignedTransport
	(*Metadata)(nil),              // 2: box.Metadata
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_box_proto_depIdxs = []int32{
	2, // 0: box.SignedTransport.Metadata:type_name -> box.Metadata
	0, // 1: box.SignedTransport.Route:type_name -> box.Route
	3, // 2: box.Metadata.Timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_box_proto_init() }
func file_box_proto_init() {
	if File_box_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_box_proto_rawDesc), len(file_box_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_box_proto_goTypes,
		DependencyIndexes: file_box_proto_depIdxs,
		EnumInfos:         file_box_proto_enumTypes,
		MessageInfos:      file_box_proto_msgTypes,
	}.Build()
	File_box_proto = out.File
	file_box_proto_goTypes = nil
	file_box_proto_depIdxs = nil
}
