// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Introduce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=AppVersion,proto3" json:"AppVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Introduce) Reset() {
	*x = Introduce{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Introduce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Introduce) ProtoMessage() {}

func (x *Introduce) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Introduce.ProtoReflect.Descriptor instead.
func (*Introduce) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *Introduce) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Introduce) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Introduce) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Salt          []byte                 `protobuf:"bytes,2,opt,name=Salt,proto3" json:"Salt,omitempty"`
	SessionKey    string                 `protobuf:"bytes,3,opt,name=SessionKey,proto3" json:"SessionKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Handshake) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *Handshake) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=FirstSeen,proto3" json:"FirstSeen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=LastSeen,proto3" json:"LastSeen,omitempty"`
	AppVersion    string                 `protobuf:"bytes,5,opt,name=AppVersion,proto3" json:"AppVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Peer) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Peer) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Peer) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ResumeRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ResumeAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=Accepted,proto3" json:"Accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAccept) Reset() {
	*x = ResumeAccept{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAccept) ProtoMessage() {}

func (x *ResumeAccept) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAccept.ProtoReflect.Descriptor instead.
func (*ResumeAccept) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeAccept) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResumeAccept) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\x03box\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\tIntroduce\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tPublicKey\x18\x02 \x01(\fR\tPublicKey\x12\x1e\n" +
	"\n" +
	"AppVersion\x18\x03 \x01(\tR\n" +
	"AppVersion\"Q\n" +
	"\tHandshake\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\fR\x03Key\x12\x12\n" +
	"\x04Salt\x18\x02 \x01(\fR\x04Salt\x12\x1e\n" +
	"\n" +
	"SessionKey\x18\x03 \x01(\tR\n" +
	"SessionKey\"\xca\x01\n" +
	"\x04Peer\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tPublicKey\x18\x02 \x01(\fR\tPublicKey\x128\n" +
	"\tFirstSeen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tFirstSeen\x126\n" +
	"\bLastSeen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bLastSeen\x12\x1e\n" +
	"\n" +
	"AppVersion\x18\x05 \x01(\tR\n" +
	"AppVersion\"C\n" +
	"\rResumeRequest\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\fR\x05Token\"B\n" +
	"\fResumeAccept\x12\x1a\n" +
	"\bAccepted\x18\x01 \x01(\bR\bAccepted\x12\x16\n" +
	"\x06Reason\x18\x02 \x01(\tR\x06ReasonB\x06Z\x04./pbb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_proto_goTypes = []any{
	(*Introduce)(nil),             // 0: box.Introduce
	(*Handshake)(nil),             // 1: box.Handshake
	(*Peer)(nil),                  // 2: box.Peer
	(*ResumeRequest)(nil),         // 3: box.ResumeRequest
	(*ResumeAccept)(nil),          // 4: box.ResumeAccept
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_model_proto_depIdxs = []int32{
	5, // 0: box.Peer.FirstSeen:type_name -> google.protobuf.Timestamp
	5, // 1: box.Peer.LastSeen:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
