// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStartServer() {
  return window['go']['main']['App']['CancelStartServer']();
}

export function ClearKeychainPassphrase() {
  return window['go']['main']['App']['ClearKeychainPassphrase']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ConfirmStopServer() {
  return window['go']['main']['App']['ConfirmStopServer']();
}

export function ConnectToServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectToServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteHistorySession(arg1) {
  return window['go']['main']['App']['DeleteHistorySession'](arg1);
}

export function DisconnectSession(arg1) {
  return window['go']['main']['App']['DisconnectSession'](arg1);
}

export function ExportLogsToFile() {
  return window['go']['main']['App']['ExportLogsToFile']();
}

export function GenerateRelayToken() {
  return window['go']['main']['App']['GenerateRelayToken']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetFingerprint() {
  return window['go']['main']['App']['GetFingerprint']();
}

export function GetFingerprintFormat() {
  return window['go']['main']['App']['GetFingerprintFormat']();
}

export function GetHistoryMessages(arg1) {
  return window['go']['main']['App']['GetHistoryMessages'](arg1);
}

export function GetHistorySessions() {
  return window['go']['main']['App']['GetHistorySessions']();
}

export function GetLibraryVersion() {
  return window['go']['main']['App']['GetLibraryVersion']();
}

export function GetLogEntries() {
  return window['go']['main']['App']['GetLogEntries']();
}

export function GetMyName() {
  return window['go']['main']['App']['GetMyName']();
}

export function GetRelayToken() {
  return window['go']['main']['App']['GetRelayToken']();
}

export function GetRelayTokens() {
  return window['go']['main']['App']['GetRelayTokens']();
}

export function GetServerRunning() {
  return window['go']['main']['App']['GetServerRunning']();
}

export function GetServerTransport() {
  return window['go']['main']['App']['GetServerTransport']();
}

export function GetSessionInfo(arg1) {
  return window['go']['main']['App']['GetSessionInfo'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetShareInfo() {
  return window['go']['main']['App']['GetShareInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStorageReady() {
  return window['go']['main']['App']['GetStorageReady']();
}

export function GetVerificationMode() {
  return window['go']['main']['App']['GetVerificationMode']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasKeychainPassphrase() {
  return window['go']['main']['App']['HasKeychainPassphrase']();
}

export function LoadHistoryMessages(arg1) {
  return window['go']['main']['App']['LoadHistoryMessages'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RefreshHistory() {
  return window['go']['main']['App']['RefreshHistory']();
}

export function RemoveRelayToken(arg1) {
  return window['go']['main']['App']['RemoveRelayToken'](arg1);
}

export function RenameHistorySession(arg1, arg2) {
  return window['go']['main']['App']['RenameHistorySession'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SaveCardPNG(arg1) {
  return window['go']['main']['App']['SaveCardPNG'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function SetDBPath(arg1) {
  return window['go']['main']['App']['SetDBPath'](arg1);
}

export function SetFingerprintFormat(arg1) {
  return window['go']['main']['App']['SetFingerprintFormat'](arg1);
}

export function SetMyName(arg1) {
  return window['go']['main']['App']['SetMyName'](arg1);
}

export function SetVerificationMode(arg1) {
  return window['go']['main']['App']['SetVerificationMode'](arg1);
}

export function StartServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3, arg4, arg5);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function SubmitPassphrase(arg1, arg2) {
  return window['go']['main']['App']['SubmitPassphrase'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function VerifyResponse(arg1, arg2) {
  return window['go']['main']['App']['VerifyResponse'](arg1, arg2);
}
