// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearKeychainPassphrase() {
  return window['go']['main']['App']['ClearKeychainPassphrase']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ConnectToServer(arg1) {
  return window['go']['main']['App']['ConnectToServer'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteHistorySession(arg1) {
  return window['go']['main']['App']['DeleteHistorySession'](arg1);
}

export function DisconnectSession(arg1) {
  return window['go']['main']['App']['DisconnectSession'](arg1);
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetFingerprint() {
  return window['go']['main']['App']['GetFingerprint']();
}

export function GetHistoryMessages(arg1) {
  return window['go']['main']['App']['GetHistoryMessages'](arg1);
}

export function GetHistorySessions() {
  return window['go']['main']['App']['GetHistorySessions']();
}

export function GetLogEntries() {
  return window['go']['main']['App']['GetLogEntries']();
}

export function GetSessionInfo(arg1) {
  return window['go']['main']['App']['GetSessionInfo'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStorageReady() {
  return window['go']['main']['App']['GetStorageReady']();
}

export function GetVerificationMode() {
  return window['go']['main']['App']['GetVerificationMode']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasKeychainPassphrase() {
  return window['go']['main']['App']['HasKeychainPassphrase']();
}

export function LoadHistoryMessages(arg1) {
  return window['go']['main']['App']['LoadHistoryMessages'](arg1);
}

export function RefreshHistory() {
  return window['go']['main']['App']['RefreshHistory']();
}

export function RenameHistorySession(arg1, arg2) {
  return window['go']['main']['App']['RenameHistorySession'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function SetDBPath(arg1) {
  return window['go']['main']['App']['SetDBPath'](arg1);
}

export function SetVerificationMode(arg1) {
  return window['go']['main']['App']['SetVerificationMode'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function SubmitPassphrase(arg1, arg2) {
  return window['go']['main']['App']['SubmitPassphrase'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function VerifyResponse(arg1, arg2) {
  return window['go']['main']['App']['VerifyResponse'](arg1, arg2);
}
