// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearKeychainPassphrase():Promise<void>;

export function ClearLogs():Promise<void>;

export function ConnectToServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteHistorySession(arg1:string):Promise<void>;

export function DisconnectSession(arg1:string):Promise<void>;

export function GetDBPath():Promise<string>;

export function GetFingerprint():Promise<Record<string, string>>;

export function GetFingerprintFormat():Promise<string>;

export function GetHistoryMessages(arg1:string):Promise<Array<main.MessageInfo>>;

export function GetHistorySessions():Promise<Array<main.HistorySessionInfo>>;

export function GetLibraryVersion():Promise<string>;

export function GetLogEntries():Promise<Array<main.LogEntryInfo>>;

export function GetMyName():Promise<string>;

export function GetRelayToken():Promise<string>;

export function GetServerRunning():Promise<boolean>;

export function GetSessionInfo(arg1:string):Promise<Record<string, any>>;

export function GetSessionMessages(arg1:string):Promise<Array<main.MessageInfo>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetStorageReady():Promise<boolean>;

export function GetVerificationMode():Promise<number>;

export function GetVersion():Promise<string>;

export function HasKeychainPassphrase():Promise<boolean>;

export function LoadHistoryMessages(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function RefreshHistory():Promise<void>;

export function RenameHistorySession(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetActiveSession(arg1:string):Promise<void>;

export function SetDBPath(arg1:string):Promise<void>;

export function SetFingerprintFormat(arg1:string):Promise<void>;

export function SetMyName(arg1:string):Promise<void>;

export function SetVerificationMode(arg1:number):Promise<void>;

export function StartServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function StopServer():Promise<void>;

export function SubmitPassphrase(arg1:string,arg2:boolean):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function VerifyResponse(arg1:number,arg2:boolean):Promise<void>;
