// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pb/relay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Register_Mode int32

const (
	Register_MODE_UNSPECIFIED Register_Mode = 0 // reserved, will be rejected
	Register_MODE_CREATE      Register_Mode = 1 // create new session
	Register_MODE_JOIN        Register_Mode = 2 // join existing session
)

// Enum value maps for Register_Mode.
var (
	Register_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_CREATE",
		2: "MODE_JOIN",
	}
	Register_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_CREATE":      1,
		"MODE_JOIN":        2,
	}
)

func (x Register_Mode) Enum() *Register_Mode {
	p := new(Register_Mode)
	*p = x
	return p
}

func (x Register_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Register_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_relay_proto_enumTypes[0].Descriptor()
}

func (Register_Mode) Type() protoreflect.EnumType {
	return &file_pb_relay_proto_enumTypes[0]
}

func (x Register_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Register_Mode.Descriptor instead.
func (Register_Mode) EnumDescriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{1, 0}
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Register
	//	*Frame_Registered
	//	*Frame_Msg
	//	*Frame_Ping
	//	*Frame_Pong
	//	*Frame_Auth
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pb_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Frame) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *Frame) GetMsg() *Message {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Frame) GetAuth() *Auth {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type Frame_Registered struct {
	Registered *Registered `protobuf:"bytes,2,opt,name=registered,proto3,oneof"`
}

type Frame_Msg struct {
	Msg *Message `protobuf:"bytes,3,opt,name=msg,proto3,oneof"`
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type Frame_Auth struct {
	Auth *Auth `protobuf:"bytes,6,opt,name=auth,proto3,oneof"` // PSK mode only, optional
}

func (*Frame_Register) isFrame_Kind() {}

func (*Frame_Registered) isFrame_Kind() {}

func (*Frame_Msg) isFrame_Kind() {}

func (*Frame_Ping) isFrame_Kind() {}

func (*Frame_Pong) isFrame_Kind() {}

func (*Frame_Auth) isFrame_Kind() {}

type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 16 bytes in MODE_JOIN; empty in MODE_CREATE = ask relay
	// to generate a random token; 16 bytes in MODE_CREATE =
	// precomputed static token (relay must accept it)
	Mode          Register_Mode `protobuf:"varint,2,opt,name=mode,proto3,enum=relayconn.Register_Mode" json:"mode,omitempty"` // required: MODE_CREATE or MODE_JOIN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_pb_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Register) GetMode() Register_Mode {
	if x != nil {
		return x.Mode
	}
	return Register_MODE_UNSPECIFIED
}

type Registered struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Token             []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                     // session token assigned by relay
	TtlSeconds        uint32                 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                        // token validity duration in seconds (0 = unknown)
	SessionTtlSeconds uint32                 `protobuf:"varint,3,opt,name=session_ttl_seconds,json=sessionTtlSeconds,proto3" json:"session_ttl_seconds,omitempty"` // paired session max lifetime (0 = no limit)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_pb_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{2}
}

func (x *Registered) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Registered) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Registered) GetSessionTtlSeconds() uint32 {
	if x != nil {
		return x.SessionTtlSeconds
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pb_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{4}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pb_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{5}
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psk           []byte                 `protobuf:"bytes,1,opt,name=psk,proto3" json:"psk,omitempty"` // pre-shared key for PSK mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_pb_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{6}
}

func (x *Auth) GetPsk() []byte {
	if x != nil {
		return x.Psk
	}
	return nil
}

var File_pb_relay_proto protoreflect.FileDescriptor

const file_pb_relay_proto_rawDesc = "" +
	"\n" +
	"\x0epb/relay.proto\x12\trelayconn\"\x98\x02\n" +
	"\x05Frame\x121\n" +
	"\bregister\x18\x01 \x01(\v2\x13.relayconn.RegisterH\x00R\bregister\x127\n" +
	"\n" +
	"registered\x18\x02 \x01(\v2\x15.relayconn.RegisteredH\x00R\n" +
	"registered\x12&\n" +
	"\x03msg\x18\x03 \x01(\v2\x12.relayconn.MessageH\x00R\x03msg\x12%\n" +
	"\x04ping\x18\x04 \x01(\v2\x0f.relayconn.PingH\x00R\x04ping\x12%\n" +
	"\x04pong\x18\x05 \x01(\v2\x0f.relayconn.PongH\x00R\x04pong\x12%\n" +
	"\x04auth\x18\x06 \x01(\v2\x0f.relayconn.AuthH\x00R\x04authB\x06\n" +
	"\x04kind\"\x8c\x01\n" +
	"\bRegister\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x12,\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x18.relayconn.Register.ModeR\x04mode\"<\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_CREATE\x10\x01\x12\r\n" +
	"\tMODE_JOIN\x10\x02\"s\n" +
	"\n" +
	"Registered\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\rR\n" +
	"ttlSeconds\x12.\n" +
	"\x13session_ttl_seconds\x18\x03 \x01(\rR\x11sessionTtlSeconds\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"\x18\n" +
	"\x04Auth\x12\x10\n" +
	"\x03psk\x18\x01 \x01(\fR\x03pskB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_relay_proto_rawDescOnce sync.Once
	file_pb_relay_proto_rawDescData []byte
)

func file_pb_relay_proto_rawDescGZIP() []byte {
	file_pb_relay_proto_rawDescOnce.Do(func() {
		file_pb_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_relay_proto_rawDesc), len(file_pb_relay_proto_rawDesc)))
	})
	return file_pb_relay_proto_rawDescData
}

var file_pb_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_relay_proto_goTypes = []any{
	(Register_Mode)(0), // 0: relayconn.Register.Mode
	(*Frame)(nil),      // 1: relayconn.Frame
	(*Register)(nil),   // 2: relayconn.Register
	(*Registered)(nil), // 3: relayconn.Registered
	(*Message)(nil),    // 4: relayconn.Message
	(*Ping)(nil),       // 5: relayconn.Ping
	(*Pong)(nil),       // 6: relayconn.Pong
	(*Auth)(nil),       // 7: relayconn.Auth
}
var file_pb_relay_proto_depIdxs = []int32{
	2, // 0: relayconn.Frame.register:type_name -> relayconn.Register
	3, // 1: relayconn.Frame.registered:type_name -> relayconn.Registered
	4, // 2: relayconn.Frame.msg:type_name -> relayconn.Message
	5, // 3: relayconn.Frame.ping:type_name -> relayconn.Ping
	6, // 4: relayconn.Frame.pong:type_name -> relayconn.Pong
	7, // 5: relayconn.Frame.auth:type_name -> relayconn.Auth
	0, // 6: relayconn.Register.mode:type_name -> relayconn.Register.Mode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_relay_proto_init() }
func file_pb_relay_proto_init() {
	if File_pb_relay_proto != nil {
		return
	}
	file_pb_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Register)(nil),
		(*Frame_Registered)(nil),
		(*Frame_Msg)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
		(*Frame_Auth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_relay_proto_rawDesc), len(file_pb_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_relay_proto_goTypes,
		DependencyIndexes: file_pb_relay_proto_depIdxs,
		EnumInfos:         file_pb_relay_proto_enumTypes,
		MessageInfos:      file_pb_relay_proto_msgTypes,
	}.Build()
	File_pb_relay_proto = out.File
	file_pb_relay_proto_goTypes = nil
	file_pb_relay_proto_depIdxs = nil
}
