// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pb/relay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Identity
	//	*Frame_Msg
	//	*Frame_Ack
	//	*Frame_Ping
	//	*Frame_Pong
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pb_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetIdentity() *Identity {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Identity); ok {
			return x.Identity
		}
	}
	return nil
}

func (x *Frame) GetMsg() *Message {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *Frame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Identity struct {
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3,oneof"`
}

type Frame_Msg struct {
	Msg *Message `protobuf:"bytes,2,opt,name=msg,proto3,oneof"`
}

type Frame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

func (*Frame_Identity) isFrame_Kind() {}

func (*Frame_Msg) isFrame_Kind() {}

func (*Frame_Ack) isFrame_Kind() {}

func (*Frame_Ping) isFrame_Kind() {}

func (*Frame_Pong) isFrame_Kind() {}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_pb_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      []byte                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // set by sender for routing; relay uses this to deliver
	Sender        []byte                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`     // set by relay when forwarding so receiver knows who sent it
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Message) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pb_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pb_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{4}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pb_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{5}
}

var File_pb_relay_proto protoreflect.FileDescriptor

const file_pb_relay_proto_rawDesc = "" +
	"\n" +
	"\x0epb/relay.proto\x12\trelayconn\"\xdc\x01\n" +
	"\x05Frame\x121\n" +
	"\bidentity\x18\x01 \x01(\v2\x13.relayconn.IdentityH\x00R\bidentity\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x12.relayconn.MessageH\x00R\x03msg\x12\"\n" +
	"\x03ack\x18\x03 \x01(\v2\x0e.relayconn.AckH\x00R\x03ack\x12%\n" +
	"\x04ping\x18\x04 \x01(\v2\x0f.relayconn.PingH\x00R\x04ping\x12%\n" +
	"\x04pong\x18\x05 \x01(\v2\x0f.relayconn.PongH\x00R\x04pongB\x06\n" +
	"\x04kind\"\x1c\n" +
	"\bIdentity\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"p\n" +
	"\aMessage\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\fR\breceiver\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"$\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04PongB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_relay_proto_rawDescOnce sync.Once
	file_pb_relay_proto_rawDescData []byte
)

func file_pb_relay_proto_rawDescGZIP() []byte {
	file_pb_relay_proto_rawDescOnce.Do(func() {
		file_pb_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_relay_proto_rawDesc), len(file_pb_relay_proto_rawDesc)))
	})
	return file_pb_relay_proto_rawDescData
}

var file_pb_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_relay_proto_goTypes = []any{
	(*Frame)(nil),    // 0: relayconn.Frame
	(*Identity)(nil), // 1: relayconn.Identity
	(*Message)(nil),  // 2: relayconn.Message
	(*Ack)(nil),      // 3: relayconn.Ack
	(*Ping)(nil),     // 4: relayconn.Ping
	(*Pong)(nil),     // 5: relayconn.Pong
}
var file_pb_relay_proto_depIdxs = []int32{
	1, // 0: relayconn.Frame.identity:type_name -> relayconn.Identity
	2, // 1: relayconn.Frame.msg:type_name -> relayconn.Message
	3, // 2: relayconn.Frame.ack:type_name -> relayconn.Ack
	4, // 3: relayconn.Frame.ping:type_name -> relayconn.Ping
	5, // 4: relayconn.Frame.pong:type_name -> relayconn.Pong
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_relay_proto_init() }
func file_pb_relay_proto_init() {
	if File_pb_relay_proto != nil {
		return
	}
	file_pb_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Identity)(nil),
		(*Frame_Msg)(nil),
		(*Frame_Ack)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_relay_proto_rawDesc), len(file_pb_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_relay_proto_goTypes,
		DependencyIndexes: file_pb_relay_proto_depIdxs,
		MessageInfos:      file_pb_relay_proto_msgTypes,
	}.Build()
	File_pb_relay_proto = out.File
	file_pb_relay_proto_goTypes = nil
	file_pb_relay_proto_depIdxs = nil
}
